targets:
  $default:
    builders:
      slang_build_runner:
        options:
          input_directory: lib/i18n
          output_directory: lib/i18n
          output_file_name: strings.g.dart
          base_locale: en
          enum_name: TablexLocale
          translate_var: tablexStrings
          fallback_strategy: base_locale
          maps:
            - filters.operators
